<Rect>:
    canvas:
        Color:
            rgb: self.color
        Rectangle:
            pos: self.pos
            size: self.size


<Man,UFO>
    canvas.before:
        PushMatrix
        Translate:
            xy: self.center_x, self.center_y
        Rotate: 
            angle:self.angle
            axis: 0, 0, 1
        Translate:
            xy: -self.center_x, -self.center_y
    canvas.after:
        PopMatrix

