# Position and size values are defined in shares of window
# Speeds are defined in shares of objects size per second

game:
  fullscreen: false 
  update_speed: 30 # count per second
  max_dead_men: 10
  increment_men_on_step: 5
  step: 30 #seconds
  debug: true 
  test_force: [0, 11] # "f" key
  score_file: score.yaml
  score_color: [1, 1, 1, 1]

world:
  gravity: 10
  size: [3, 1]
  background_color: [.1, .1, .11]
  ground:
    color: [0, 0, 0]
    border_color: [1, 1, 1]
    height: .1
    border_width: .002
  objects:
  # positions should be defined in range [0, <world.width>]
  - size: [.15, .15] 
    image: graphics/moon.png 
    pos: [1.5, .75]
  - size: [.27, .27]
    image: graphics/house_1.png
    pos: [1, .1]
  - size: [.2, .1]
    image: graphics/car_1.png
    pos: [2.5, .1]
  - size: [.2, .1]
    image: graphics/car_1.png
    pos: [1.2, .1]
  - size: [.3, .3]
    image: graphics/tree_1.png
    pos: [.2, .1]
  - size: [.3, .3]
    image: graphics/tree_1.png
    pos: [.25, .1]
  - size: [.3, .3]
    image: graphics/tree_1.png
    pos: [.5, .1]
  - size: [.3, .3]
    image: graphics/tree_1.png
    pos: [2, .1]
  - size: [.3, .3]
    image: graphics/tree_2.png
    pos: [1.5, .1]

ufo:
  ray:
    force: 12
    angle: 40
    size: [.4, .8]
    image: graphics/ray.atlas
    anim_speed: 12
  pendulum:
    amplitude_angle: 30 
    swing_factor: 400 # angle per sec
    gravity_factor: 800 # angle per sec
    braking_factor: .01 # angle per sec
  image: graphics/ufo.atlas
  anim_speed: 10
  max_speed: .01 # absolute value
  acceleration: .01 # per second
  braking: 0.002
  control: 'arrows' # 'gyroscope' | 'arrows' | 'touch_screen'
  size: [.3, .15]
  y: .9

man:
  speed: .01 
  dspeed: .006
  deadly_fly_speed: 480 # when touches ground 
  fly_rotation_speed: 60 # degrees per second
  right_image: graphics/right_man.atlas
  left_image: graphics/left_man.atlas
  size: .1

